name: feature-branch
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node & NPM
        uses: actions/setup-node@v3
      - name: Install node modules
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test & Coverage
        run: npm run test:lib-coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
      - name: Build
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
